/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paymentapp;

import java.awt.Color;
import java.math.BigInteger;
import java.util.Random;
import java.security.*;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.RSAPublicKeySpec;
import java.util.Arrays;
import java.util.Base64;
import javax.swing.JOptionPane;


/**
 *
 * @author duong
 */
public class KetNoiThe extends javax.swing.JFrame {
    public static int enterMoney;

    /**
     * Creates new form KetNoiThe
     */
//    Customer customer;
    public KetNoiThe() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonConnectToCard = new javax.swing.JButton();
        jButtonCardInit = new javax.swing.JButton();
        statusConnect = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btOpenCard = new javax.swing.JButton();
        btClearCard = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pfCheckPIN = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tpStatus = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBirth = new javax.swing.JTextField();
        tfPhone = new javax.swing.JTextField();
        tfWallet = new javax.swing.JFormattedTextField();
        btChangeBirth = new javax.swing.JButton();
        btChangePhone = new javax.swing.JButton();
        btChangePIN = new javax.swing.JButton();
        btChangeName = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btSave = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btPayment = new javax.swing.JButton();
        btLoad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kết Nối", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        jButtonConnectToCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonConnectToCard.setText("Kết nối đến thẻ");
        jButtonConnectToCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectToCardActionPerformed(evt);
            }
        });

        jButtonCardInit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCardInit.setText("Khởi tạo thẻ mới");
        jButtonCardInit.setEnabled(false);
        jButtonCardInit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCardInitActionPerformed(evt);
            }
        });

        statusConnect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        statusConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusConnectActionPerformed(evt);
            }
        });

        jLabel1.setText("Trạng thái");

        btOpenCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btOpenCard.setText("Mở thẻ");
        btOpenCard.setEnabled(false);
        btOpenCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpenCardActionPerformed(evt);
            }
        });

        btClearCard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btClearCard.setText("Xóa thẻ");
        btClearCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearCardActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Nhập mã PIN: ");

        pfCheckPIN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pfCheckPIN.setEnabled(false);
        pfCheckPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfCheckPINActionPerformed(evt);
            }
        });

        btLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLogin.setText("Đồng ý");
        btLogin.setEnabled(false);
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        tpStatus.setBackground(new java.awt.Color(240, 240, 240));
        tpStatus.setBorder(null);
        tpStatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tpStatus.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tpStatus.setEnabled(false);
        jScrollPane1.setViewportView(tpStatus);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLogin)
                .addGap(58, 58, 58))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonConnectToCard, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(statusConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jButtonCardInit, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(btOpenCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btClearCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfCheckPIN)))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConnectToCard)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(statusConnect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonCardInit)
                .addGap(18, 18, 18)
                .addComponent(btOpenCard)
                .addGap(18, 18, 18)
                .addComponent(btClearCard)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfCheckPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 440));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thẻ Thanh Toán", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 24), new java.awt.Color(153, 0, 0))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin thẻ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Tên chủ thẻ:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Ngày sinh:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("SĐT:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Số dư ví: ");

        tfID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfID.setEnabled(false);
        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        tfName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfName.setEnabled(false);
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfBirth.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfBirth.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfBirth.setEnabled(false);

        tfPhone.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfPhone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfPhone.setEnabled(false);
        tfPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneActionPerformed(evt);
            }
        });

        tfWallet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N
        tfWallet.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tfWallet.setEnabled(false);
        tfWallet.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tfWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWalletActionPerformed(evt);
            }
        });

        btChangeBirth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btChangeBirth.setText("Sửa");
        btChangeBirth.setEnabled(false);
        btChangeBirth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeBirthActionPerformed(evt);
            }
        });

        btChangePhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btChangePhone.setText("Sửa");
        btChangePhone.setEnabled(false);
        btChangePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangePhoneActionPerformed(evt);
            }
        });

        btChangePIN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btChangePIN.setText("Đổi mã PIN");
        btChangePIN.setEnabled(false);
        btChangePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangePINActionPerformed(evt);
            }
        });

        btChangeName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btChangeName.setText("Sửa");
        btChangeName.setEnabled(false);
        btChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btChangeNameActionPerformed(evt);
            }
        });
        btChangeName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btChangeNamePropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("VNĐ");

        btSave.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btSave.setText("Lưu");
        btSave.setEnabled(false);
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btChangeBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfWallet, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btChangePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(btChangePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChangeName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btChangeBirth)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btChangePhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfWallet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btChangePIN)
                    .addComponent(btSave))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giao dịch", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        btPayment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btPayment.setText("Thanh toán");
        btPayment.setEnabled(false);
        btPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPaymentActionPerformed(evt);
            }
        });

        btLoad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLoad.setText("Nạp tiền");
        btLoad.setEnabled(false);
        btLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 470, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusConnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusConnectActionPerformed

    
    public static boolean isConnect = false;
    PaymentApp card = new PaymentApp();
    private void jButtonConnectToCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectToCardActionPerformed
        // TODO add your handling code here:
        if (!isConnect) {
            if (card.connectCard()) {
                isConnect = true;
                jButtonConnectToCard.setText("Ngắt kết nối");
                jButtonConnectToCard.setForeground(Color.RED);
                statusConnect.setText("Thành công");
                jButtonCardInit.setEnabled(true);
                pfCheckPIN.setEnabled(isConnect);
                btLogin.setEnabled(isConnect);
                btOpenCard.setEnabled(isConnect);
                btClearCard.setEnabled(isConnect);
                btChangeName.setEnabled(isConnect);
                btChangeBirth.setEnabled(isConnect);
                btChangePhone.setEnabled(isConnect);
                btChangePIN.setEnabled(isConnect);
                btSave.setEnabled(isConnect);
                btPayment.setEnabled(isConnect);
                btLoad.setEnabled(isConnect);
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Chưa connect được đến applet");
                isConnect = false;
                jButtonConnectToCard.setText("Kết nối đến thẻ");
                statusConnect.setForeground(Color.BLACK);
                
            }
        }
        else{
            if (card.disconnect()) {
                isConnect = false;
                pfCheckPIN.setEnabled(isConnect);
                btLogin.setEnabled(isConnect);
                btOpenCard.setEnabled(isConnect);
                btClearCard.setEnabled(isConnect);
                jButtonConnectToCard.setText("Kết nối đến thẻ");
                jButtonConnectToCard.setForeground(Color.BLACK);
                statusConnect.setText("");
                jButtonCardInit.setEnabled(false);
                tfID.setText("");
                tfName.setText("");
                tfBirth.setText("");
                tfPhone.setText("");
                tfWallet.setText("");
                pfCheckPIN.setText("");
                tpStatus.setText("");
                btChangeName.setEnabled(isConnect);
                btChangeBirth.setEnabled(isConnect);
                btChangePhone.setEnabled(isConnect);
                btChangePIN.setEnabled(isConnect);
                btSave.setEnabled(isConnect);
                btPayment.setEnabled(isConnect);
                btLoad.setEnabled(isConnect);
                
//                resetButton();
            }
        }
    }//GEN-LAST:event_jButtonConnectToCardActionPerformed
    boolean resu1t = true;
    private void jButtonCardInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCardInitActionPerformed
        // TODO add your handling code here:
        TaoTheMoi taoTheMoi = new TaoTheMoi();
        taoTheMoi.setVisible(isConnect);
        

    }//GEN-LAST:event_jButtonCardInitActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneActionPerformed

    private void tfWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWalletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWalletActionPerformed

    private void pfCheckPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfCheckPINActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_pfCheckPINActionPerformed

    int count = 0;
    boolean result = false;
    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed

        String pin = new String(pfCheckPIN.getPassword());
//        System.out.println(pin);
        
        String ranString = randomString().toLowerCase();
        byte[] dataBytes = Base64.getEncoder().encode(ranString.getBytes());
//        System.out.println(ranString);
//        System.out.println(Arrays.toString(dataBytes));
        String resData = card.authCard(ranString);
        String resRanString = resData.substring(128);
//        String resRanStrings = resData.substring(0, 128);
//        byte[] sigToVerify = Base64.getDecoder().decode(resRanString);
//        System.out.println(resRanString);
 
        try {
            String expAndMod = PaymentApp.idAndPubkey.get(Customer.getId());
            System.out.println(expAndMod);
            
            String exp = expAndMod.substring(0, 6);
//            System.out.println(exp);
            String mod = expAndMod.substring(6);
//            System.out.println(mod);
            
            RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(new BigInteger(mod, 16), new BigInteger(exp,16));
            KeyFactory factory = KeyFactory.getInstance("RSA");
            PublicKey pubKey = factory.generatePublic(pubKeySpec);

            Signature signature = Signature.getInstance("SHA1withRSA");
            signature.initVerify(pubKey);
            signature.update(dataBytes);
            result = signature.verify(resRanString.getBytes());
            
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | InvalidKeyException | SignatureException  e) {
            System.out.println("Error" + e);
        }
        
        
        
        
        if (resu1t == true) {
            if (pin.length() >= 6) {
                String checkPIN = card.authPIN(pin);
                System.out.println(checkPIN);
                
                switch (checkPIN) {
                    case "9000":
                        tpStatus.setText("Đăng nhập thành công");
                        count = 0;

                        tfID.setText(Customer.getId());
                        tfName.setText(Customer.getName());
                        tfBirth.setText(Customer.getBirth());
                        tfPhone.setText(Customer.getPhone());
                        tfWallet.setText(Customer.getWallet());
                        pfCheckPIN.setEnabled(false);
                        btLogin.setEnabled(false);

                        break;

                    case "19000":
                        tpStatus.setText("Còn " + (3-count) + "nhập sai PIN");
                        count++;
                        break;
                    case "09000":
                        tpStatus.setText("Thẻ bị khóa");
                        count = 0;
                        btLogin.setEnabled(false);
                        pfCheckPIN.setEnabled(false);
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi đăng nhập");
                        break;
                }
            }
        }else{JOptionPane.showMessageDialog(rootPane, "Xác thực thất bại");}
        


    }//GEN-LAST:event_btLoginActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed
//    boolean changeName = false;
    private void btChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeNameActionPerformed
        // TODO add your handling code here:
        btChangeName.setForeground(Color.RED);
        tfName.setEnabled(true);
        
    }//GEN-LAST:event_btChangeNameActionPerformed

    private void btChangeNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btChangeNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_btChangeNamePropertyChange

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        
        if(card.changeName(tfName.getText()) == true){
            tfName.setEnabled(false);
            btChangeName.setForeground(Color.BLACK);
            Customer.setName(tfName.getText());
        }
        if (card.changeBirth(tfBirth.getText()) == true) {
            tfBirth.setEnabled(false);
            btChangeBirth.setForeground(Color.BLACK);
            Customer.setBirth(tfBirth.getText());
        }
        if (card.changePhoneNumber(tfPhone.getText()) == true) {
            tfPhone.setEnabled(false);
            btChangePhone.setForeground(Color.BLACK);
            Customer.setPhone(tfPhone.getText());
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Lỗi khi lưu");
        }
        
        
    }//GEN-LAST:event_btSaveActionPerformed

    private void btChangeBirthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangeBirthActionPerformed
        // TODO add your handling code here:
        btChangeBirth.setForeground(Color.RED);
        tfBirth.setEnabled(true);
    }//GEN-LAST:event_btChangeBirthActionPerformed

    private void btChangePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangePhoneActionPerformed
        // TODO add your handling code here:
        btChangePhone.setForeground(Color.RED);
        tfPhone.setEnabled(true);
    }//GEN-LAST:event_btChangePhoneActionPerformed

    private void btChangePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btChangePINActionPerformed
        // TODO add your handling code here:
        DoiMaPIN doiMaPIN = new DoiMaPIN();
        doiMaPIN.setVisible(true);
    }//GEN-LAST:event_btChangePINActionPerformed

    private void btOpenCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpenCardActionPerformed
        // TODO add your handling code here:
        btLogin.setEnabled(true);
        pfCheckPIN.setEnabled(true);
    }//GEN-LAST:event_btOpenCardActionPerformed

    private void btClearCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearCardActionPerformed
        // TODO add your handling code here:
        if (card.disconnect()) {
                isConnect = false;
                pfCheckPIN.setEnabled(isConnect);
                btLogin.setEnabled(isConnect);
                btOpenCard.setEnabled(isConnect);
                btClearCard.setEnabled(isConnect);
                jButtonConnectToCard.setText("Kết nối đến thẻ");
                jButtonConnectToCard.setForeground(Color.BLACK);
                statusConnect.setText("");
                jButtonCardInit.setEnabled(false);
                tfID.setText("");
                tfName.setText("");
                tfBirth.setText("");
                tfPhone.setText("");
                tfWallet.setText("");
                pfCheckPIN.setText("");
                tpStatus.setText("");
                btChangeName.setEnabled(isConnect);
                btChangeBirth.setEnabled(isConnect);
                btChangePhone.setEnabled(isConnect);
                btChangePIN.setEnabled(isConnect);
                btSave.setEnabled(isConnect);
                btPayment.setEnabled(isConnect);
                btLoad.setEnabled(isConnect);
                
                Customer.setId("");
                Customer.setName("");
                Customer.setBirth("");
                Customer.setPhone("");
                Customer.setWallet("");
                Customer.setPin("");
                
                JOptionPane.showMessageDialog(rootPane, "Dữ liệu đã bị xóa");
                
//                resetButton();
            }
        
    }//GEN-LAST:event_btClearCardActionPerformed

    private void btLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadActionPerformed
        // TODO add your handling code her
        NapTien napTien = new NapTien();
        napTien.setVisible(true);

    }//GEN-LAST:event_btLoadActionPerformed

    private void btPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPaymentActionPerformed
        // TODO add your handling code here
        ThanhToan thanhToan = new ThanhToan();
        thanhToan.setVisible(true);
    }//GEN-LAST:event_btPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new KetNoiThe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btChangeBirth;
    private javax.swing.JButton btChangeName;
    private javax.swing.JButton btChangePIN;
    private javax.swing.JButton btChangePhone;
    private javax.swing.JButton btClearCard;
    private javax.swing.JButton btLoad;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btOpenCard;
    private javax.swing.JButton btPayment;
    private javax.swing.JButton btSave;
    private javax.swing.JButton jButtonCardInit;
    private javax.swing.JButton jButtonConnectToCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pfCheckPIN;
    private javax.swing.JTextField statusConnect;
    private javax.swing.JTextField tfBirth;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JFormattedTextField tfWallet;
    private javax.swing.JTextPane tpStatus;
    // End of variables declaration//GEN-END:variables


    public String randomString() {
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 3) {
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;
    }
    
}
