/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcard03;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author laihi
 */
public class CustomerFrame extends javax.swing.JFrame {
    private ConnectJavaCard host;
    public boolean  isConnect;
    public int tiendichvu=0;
    public int tienthuc ;
    public int dichvuyeucau = 0;
    public long tienngay = 0;
    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        host = new ConnectJavaCard();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        button_dangnhap = new javax.swing.JButton();
        button_connect = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        text_pin = new javax.swing.JPasswordField();
        panel_mokhoaphong = new javax.swing.JPanel();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        panel_thongtincanhan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_doimapin = new javax.swing.JButton();
        text_cccd = new javax.swing.JTextField();
        text_hoten = new javax.swing.JTextField();
        text_phong = new javax.swing.JTextField();
        text_ngaydk = new javax.swing.JTextField();
        text_mapin = new javax.swing.JTextField();
        text_tien = new javax.swing.JTextField();
        anhdaidien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        text_tiennhapvao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_tiencanthanhtoan = new javax.swing.JTextField();
        button_thanhtoan = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        text_dichvuyeucau = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        text_ngayhientai = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        text_ngaydangki = new javax.swing.JTextField();
        text_ngayo = new javax.swing.JTextField();
        panel_dichvu = new javax.swing.JPanel();
        button_casino = new javax.swing.JButton();
        button_ok = new javax.swing.JButton();
        button_spa = new javax.swing.JButton();
        button_bar = new javax.swing.JButton();
        button_nhahang = new javax.swing.JButton();
        text_tiendichvu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        button_casino_uncheck = new javax.swing.JButton();
        button_spa_uncheck = new javax.swing.JButton();
        button_bar_uncheck = new javax.swing.JButton();
        button_nhahang_uncheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table.setEnabled(false);
        Table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table.setVerifyInputWhenFocusTarget(false);

        button_dangnhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_dangnhap.setText("Đăng nhập");
        button_dangnhap.setEnabled(false);
        button_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dangnhapActionPerformed(evt);
            }
        });

        button_connect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_connect.setText("Kết nối thẻ");
        button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connectActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PIN:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(button_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        Table.addTab("Đăng nhập", jPanel4);

        button_1.setBackground(new java.awt.Color(255, 255, 255));
        button_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_1.setText("Phòng 1");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_2.setText("Phòng 2");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_3.setText("Phòng 3");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_5.setText("Phòng 5");
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_6.setText("Phòng 6");
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_7.setText("Phòng 7");
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_8.setText("Phòng 8");
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_4.setText("Phòng 4");
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mokhoaphongLayout = new javax.swing.GroupLayout(panel_mokhoaphong);
        panel_mokhoaphong.setLayout(panel_mokhoaphongLayout);
        panel_mokhoaphongLayout.setHorizontalGroup(
            panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panel_mokhoaphongLayout.setVerticalGroup(
            panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mokhoaphongLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Table.addTab("Mở khóa phòng", panel_mokhoaphong);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Số CCCD:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên chủ thẻ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phòng:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngày ĐK:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PIN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tiền trong thẻ:");

        button_doimapin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_doimapin.setText("Đổi mã pin");
        button_doimapin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_doimapinActionPerformed(evt);
            }
        });

        text_cccd.setEnabled(false);

        text_hoten.setEnabled(false);

        text_phong.setEnabled(false);

        text_ngaydk.setEnabled(false);

        text_tien.setEnabled(false);
        text_tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tienActionPerformed(evt);
            }
        });

        anhdaidien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ảnh đại diện");

        javax.swing.GroupLayout panel_thongtincanhanLayout = new javax.swing.GroupLayout(panel_thongtincanhan);
        panel_thongtincanhan.setLayout(panel_thongtincanhanLayout);
        panel_thongtincanhanLayout.setHorizontalGroup(
            panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(text_cccd))
                            .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                                    .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(51, 51, 51)
                                    .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(text_tien, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                                .addComponent(text_mapin)
                                                .addComponent(text_ngaydk))
                                            .addComponent(text_phong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(text_hoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(52, 52, 52)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(button_doimapin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_thongtincanhanLayout.setVerticalGroup(
            panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(text_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_ngaydk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(anhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_mapin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(button_doimapin)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        Table.addTab("Thông in cá nhân", panel_thongtincanhan);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nhập số tiền cần thanh toán");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Số tiền cần thanh toán");

        button_thanhtoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_thanhtoan.setText("Thanh toán");
        button_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thanhtoanActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Dịch vụ đang dùng");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Ngày đăng kí");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Ngày hiện tại");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(button_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_tiencanthanhtoan)
                            .addComponent(text_tiennhapvao)
                            .addComponent(text_ngaydangki, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(text_ngayhientai, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(text_ngayo))
                            .addComponent(text_dichvuyeucau))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_ngaydangki, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ngayhientai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(text_ngayo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(text_dichvuyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(text_tiencanthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tiennhapvao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(16, 16, 16)
                .addComponent(button_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        Table.addTab("Thanh toán thẻ", jPanel1);

        button_casino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_casino.setText("Chọn mua");
        button_casino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_casinoActionPerformed(evt);
            }
        });

        button_ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_spa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_spa.setText("Chọn mua");
        button_spa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_spaActionPerformed(evt);
            }
        });

        button_bar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_bar.setText("Chọn mua");
        button_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_barActionPerformed(evt);
            }
        });

        button_nhahang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_nhahang.setText("Chọn mua");
        button_nhahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhahangActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tiền dịch vụ:");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh2/casino2.jpg"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh2/spa2.jpg"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh2/bar2.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh2/restaurant2.jpg"))); // NOI18N
        jLabel15.setText("jLabel12");

        button_casino_uncheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_casino_uncheck.setText("Bỏ mua");
        button_casino_uncheck.setEnabled(false);
        button_casino_uncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_casino_uncheckActionPerformed(evt);
            }
        });

        button_spa_uncheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_spa_uncheck.setText("Bỏ mua");
        button_spa_uncheck.setEnabled(false);
        button_spa_uncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_spa_uncheckActionPerformed(evt);
            }
        });

        button_bar_uncheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_bar_uncheck.setText("Bỏ mua");
        button_bar_uncheck.setEnabled(false);
        button_bar_uncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bar_uncheckActionPerformed(evt);
            }
        });

        button_nhahang_uncheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_nhahang_uncheck.setText("Bỏ mua");
        button_nhahang_uncheck.setEnabled(false);
        button_nhahang_uncheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhahang_uncheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dichvuLayout = new javax.swing.GroupLayout(panel_dichvu);
        panel_dichvu.setLayout(panel_dichvuLayout);
        panel_dichvuLayout.setHorizontalGroup(
            panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dichvuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_casino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_casino_uncheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dichvuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_spa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_spa_uncheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_bar_uncheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button_nhahang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_nhahang_uncheck, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(panel_dichvuLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(text_tiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_dichvuLayout.setVerticalGroup(
            panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dichvuLayout.createSequentialGroup()
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dichvuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_spa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(button_casino)
                                .addComponent(button_nhahang))
                            .addComponent(button_bar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_nhahang_uncheck)
                    .addComponent(button_bar_uncheck)
                    .addComponent(button_spa_uncheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_casino_uncheck))
                .addGap(25, 25, 25)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Table.addTab("Dịch vụ yêu cầu", panel_dichvu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table)
        );

        Table.getAccessibleContext().setAccessibleName("");
        Table.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_tienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tienActionPerformed

    private void button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connectActionPerformed
      if(!isConnect){
            if(host.connectapplet()){         
               isConnect=true;
               button_dangnhap.setEnabled(true);
           }else{
                JOptionPane.showMessageDialog(this, "Chưa connect được đến applet");
                isConnect = false;
           }
       }else{
       }        
    }//GEN-LAST:event_button_connectActionPerformed

   // public String mapin2;
    int count=0;
    private void button_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dangnhapActionPerformed
    
      
      String pin = new String(text_pin.getPassword());
      if (pin.length() == 6) {
            String checkPIN = host.authPIN(pin);
            System.out.println(checkPIN+"faewfawefwa");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                        count=0;
                        Table.setEnabled(true);             
                        anhdaidien.setIcon(new ImageIcon( host.DownloadImage()));           
                        String[] data = host.getData().split("@");
                        
                        text_cccd.setText(data[0]);
                       // text_hoten.setText(data[1]);
                        System.out.println(" dich vu yeu cau hien gio la" + data[2]);    
                        dichvuyeucau = Integer.valueOf(data[2]);
                        text_phong.setText(data[5]);
                        text_ngaydk.setText(data[6]);
                    //    text_mapin.setText(data[7]);
                      //ss  text_mapin.setText("******");
                        text_tien.setText(data[7]);     
                      //  text_tiencanthanhtoan.setText(tienngay+tienthuc+data[8]);
                       
                        
                     //   mapin2 = data[7];
                       
//                           text_cccd.setText(data[0]);
//                           text_hoten.setText(data[1]);
//                           System.out.println(" dich vu yeu cau hien gio la" + data[2]);
                        //034200005365@Lai Van Hieu@0@12-11-2000@0981136706@0@25-5-2022@123456@0
                           
                                          
                           
                
                        
                        
                        
                        
                        tienthuc = Integer.valueOf(data[7]);
                        if(dichvuyeucau==1){button_casino.setEnabled(false); text_dichvuyeucau.setText("Casino");}
                        else if(dichvuyeucau==3){button_spa.setEnabled(false); text_dichvuyeucau.setText("Spa");}
                        else if(dichvuyeucau==5){button_bar.setEnabled(false); text_dichvuyeucau.setText("Bar");}
                        else if(dichvuyeucau==10){button_nhahang.setEnabled(false); text_dichvuyeucau.setText("Nha hang");}
                        else if(dichvuyeucau==4){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa");
                        }
                        else if(dichvuyeucau==6){
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Bar");
                        }
                        else if(dichvuyeucau==11){
                            button_casino.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Nha hang");
                        }
                        else if(dichvuyeucau==8){
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Bar");
                        }
                        else if(dichvuyeucau==13){
                            button_spa.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Nha hang");
                        }
                        else if(dichvuyeucau==15){
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==9){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Bar");
                        }
                        else if(dichvuyeucau==14){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Nha hang");
                        }
                        else if(dichvuyeucau==16){
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==18){
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==19){
                            button_spa.setEnabled(false);
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Bar --- Nha hang");
                        }
                        DateFormat simpleDateFormat = new SimpleDateFormat("dd-MM-yyyy");
                        Date currentDate = new Date();
                        Date date1 = null;
                        Date date2 = null;
                        {
                       try {
                            date1 = simpleDateFormat.parse(data[6]);
                        } catch (ParseException ex) {
                           Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        }
                        String endDate = simpleDateFormat.format(currentDate);
            {
                try {
                    date2 = simpleDateFormat.parse(endDate);
                } catch (ParseException ex) {
                    Logger.getLogger(CustomerFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
                        long getDiff = date2.getTime() - date1.getTime();

                        long getDaysDiff = getDiff / (24 * 60 * 60 * 1000); 
                        text_ngayhientai.setText(date2+"");
                        text_ngaydangki.setText(date1+"");
                        tienngay = getDaysDiff*500;
                        text_ngayo.setText(getDaysDiff+"=> " +tienngay+" VNĐ");
                        text_tiencanthanhtoan.setText((tienngay+tienthuc)+"");
                        
                        break;

                  case "19000":
                       // host.wrongPIN();
                        JOptionPane.showMessageDialog(this, "Còn " + (3-count) + " nhập sai PIN");
                        count++;
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Thẻ đã bị khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi đăng nhập");
                        break;
        }}else{
       JOptionPane.showMessageDialog(rootPane, "Mật khẩu phải gồm 6 số");
      }
    }//GEN-LAST:event_button_dangnhapActionPerformed

    private void button_doimapinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_doimapinActionPerformed
      //  if(!text_mapin.getText().equals(mapin2)){
            System.out.println("thay doi pin");
            if(host.changePIN(text_mapin.getText())){
                System.out.println("thay doi pin  thanh cong");
                JOptionPane.showMessageDialog(this, "Thay pin thành công");   
       //     }
        }
    }//GEN-LAST:event_button_doimapinActionPerformed

    private void button_casinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_casinoActionPerformed
        // TODO add your handling code here:
        tiendichvu +=100;
        dichvuyeucau +=1;
        text_tiendichvu.setText(tiendichvu+"");
        button_casino_uncheck.setEnabled(true);
        button_casino.setEnabled(false);
    }//GEN-LAST:event_button_casinoActionPerformed

    private void button_spaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_spaActionPerformed
       tiendichvu +=200;
       dichvuyeucau +=3;
       text_tiendichvu.setText(tiendichvu+"");
       button_spa_uncheck.setEnabled(true);
       button_spa.setEnabled(false);
    }//GEN-LAST:event_button_spaActionPerformed

    private void button_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_barActionPerformed
        // TODO add your handling code here:
        tiendichvu +=300;
        dichvuyeucau+=5;
        text_tiendichvu.setText(tiendichvu+"");
        button_bar_uncheck.setEnabled(true);
        button_bar.setEnabled(false);
    }//GEN-LAST:event_button_barActionPerformed

    private void button_nhahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhahangActionPerformed
        // TODO add your handling code here:
        tiendichvu +=600;
        dichvuyeucau+=10;
        text_tiendichvu.setText(tiendichvu+"");
        button_nhahang_uncheck.setEnabled(true);
        button_nhahang.setEnabled(false);
    }//GEN-LAST:event_button_nhahangActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        if(tiendichvu==0){
            JOptionPane.showMessageDialog(this, "Không có dịch vụ nào được lựa chọn");   
        }else{
        tienthuc+= tiendichvu;
        text_tien.setText(tienthuc+"");
        text_tiencanthanhtoan.setText(tienngay+tienthuc+"");
        tiendichvu=0;
        text_tiendichvu.setText("");
        host.changeWallet(tienthuc+"");
        host.changeDichvuyeucau(dichvuyeucau+"");
        JOptionPane.showMessageDialog(this, "Rất vui lòng phục vụ quý khách");   
        button_bar_uncheck.setEnabled(false);
        button_casino_uncheck.setEnabled(false);
        button_nhahang_uncheck.setEnabled(false);
        button_spa_uncheck.setEnabled(false);
        }
                    if(dichvuyeucau==1){button_casino.setEnabled(false); text_dichvuyeucau.setText("Casino");}
                        else if(dichvuyeucau==3){button_spa.setEnabled(false); text_dichvuyeucau.setText("Spa");}
                        else if(dichvuyeucau==5){button_bar.setEnabled(false); text_dichvuyeucau.setText("Bar");}
                        else if(dichvuyeucau==10){button_nhahang.setEnabled(false); text_dichvuyeucau.setText("Nha hang");}
                        else if(dichvuyeucau==4){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa");
                        }
                        else if(dichvuyeucau==6){
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Bar");
                        }
                        else if(dichvuyeucau==11){
                            button_casino.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Nha hang");
                        }
                        else if(dichvuyeucau==8){
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Bar");
                        }
                        else if(dichvuyeucau==13){
                            button_spa.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Nha hang");
                        }
                        else if(dichvuyeucau==15){
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==9){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Bar");
                        }
                        else if(dichvuyeucau==14){
                            button_casino.setEnabled(false);
                            button_spa.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Nha hang");
                        }
                        else if(dichvuyeucau==16){
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==18){
                            button_spa.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Spa --- Bar --- Nha hang");
                        }
                        else if(dichvuyeucau==19){
                            button_spa.setEnabled(false);
                            button_casino.setEnabled(false);
                            button_bar.setEnabled(false);
                            button_nhahang.setEnabled(false);
                            text_dichvuyeucau.setText("Casino --- Spa --- Bar --- Nha hang");
                        }
                        
    }//GEN-LAST:event_button_okActionPerformed

    private void button_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thanhtoanActionPerformed
        // TODO add your handling code here:
        int tien3 = Integer.valueOf(text_tiencanthanhtoan.getText());
        int tiennhapvao = Integer.valueOf(text_tiennhapvao.getText());
        if(tiennhapvao!=tien3){
              JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng số tiền cần thanh toán");
        }
        else{
          // int b = tien3-tiennhapvao;
           text_tien.setText(0+"");
           text_tiencanthanhtoan.setText(0+"");
           host.changeWallet(0+"");
           JOptionPane.showMessageDialog(this, "Thanh toán thành công");   
        }  
    }//GEN-LAST:event_button_thanhtoanActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
            String maphong = "01";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
         String maphong = "02";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
       String maphong = "03";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
       String maphong = "04";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
         String maphong = "05";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
       String maphong = "06";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
            String maphong = "07";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
            String maphong = "08";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_8ActionPerformed

    private void button_casino_uncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_casino_uncheckActionPerformed
        // TODO add your handling code here:
        tiendichvu -=100;
        dichvuyeucau-=1;
        text_tiendichvu.setText(tiendichvu+"");
        button_casino_uncheck.setEnabled(false);
        button_casino.setEnabled(true);
    }//GEN-LAST:event_button_casino_uncheckActionPerformed

    private void button_spa_uncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_spa_uncheckActionPerformed
        // TODO add your handling code here:
        tiendichvu -=200;
        dichvuyeucau-=3;
        text_tiendichvu.setText(tiendichvu+"");
        button_spa_uncheck.setEnabled(false);
        button_spa.setEnabled(true);
    }//GEN-LAST:event_button_spa_uncheckActionPerformed

    private void button_bar_uncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bar_uncheckActionPerformed
        // TODO add your handling code here:
        tiendichvu -=300;
        dichvuyeucau-=5;
        text_tiendichvu.setText(tiendichvu+"");
        button_bar_uncheck.setEnabled(false);
        button_bar.setEnabled(true);
    }//GEN-LAST:event_button_bar_uncheckActionPerformed

    private void button_nhahang_uncheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhahang_uncheckActionPerformed
        // TODO add your handling code here:
        tiendichvu -=600;
        dichvuyeucau-=10;
        text_tiendichvu.setText(tiendichvu+"");
        button_nhahang_uncheck.setEnabled(false);
        button_nhahang.setEnabled(true);
    }//GEN-LAST:event_button_nhahang_uncheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Table;
    private javax.swing.JLabel anhdaidien;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_bar;
    private javax.swing.JButton button_bar_uncheck;
    private javax.swing.JButton button_casino;
    private javax.swing.JButton button_casino_uncheck;
    private javax.swing.JButton button_connect;
    private javax.swing.JButton button_dangnhap;
    private javax.swing.JButton button_doimapin;
    private javax.swing.JButton button_nhahang;
    private javax.swing.JButton button_nhahang_uncheck;
    private javax.swing.JButton button_ok;
    private javax.swing.JButton button_spa;
    private javax.swing.JButton button_spa_uncheck;
    private javax.swing.JButton button_thanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panel_dichvu;
    private javax.swing.JPanel panel_mokhoaphong;
    private javax.swing.JPanel panel_thongtincanhan;
    private javax.swing.JTextField text_cccd;
    private javax.swing.JTextField text_dichvuyeucau;
    private javax.swing.JTextField text_hoten;
    private javax.swing.JTextField text_mapin;
    private javax.swing.JTextField text_ngaydangki;
    private javax.swing.JTextField text_ngaydk;
    private javax.swing.JTextField text_ngayhientai;
    private javax.swing.JTextField text_ngayo;
    private javax.swing.JTextField text_phong;
    private javax.swing.JPasswordField text_pin;
    private javax.swing.JTextField text_tien;
    private javax.swing.JTextField text_tiencanthanhtoan;
    private javax.swing.JTextField text_tiendichvu;
    private javax.swing.JTextField text_tiennhapvao;
    // End of variables declaration//GEN-END:variables
}
