/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcard03;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author laihi
 */
public class CustomerFrame extends javax.swing.JFrame {
    private ConnectJavaCard host;
    public boolean  isConnect;
    public int tiendichvu;
    public int tienthuc ;
    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        host = new ConnectJavaCard();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Table = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        button_dangnhap = new javax.swing.JButton();
        button_connect = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        text_pin = new javax.swing.JPasswordField();
        panel_mokhoaphong = new javax.swing.JPanel();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        panel_thongtincanhan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        button_doimapin = new javax.swing.JButton();
        text_cccd = new javax.swing.JTextField();
        text_hoten = new javax.swing.JTextField();
        text_phong = new javax.swing.JTextField();
        text_ngaydk = new javax.swing.JTextField();
        text_mapin = new javax.swing.JTextField();
        text_tien = new javax.swing.JTextField();
        anhdaidien = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        text_tiennhapvao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_tiencanthanhtoan = new javax.swing.JTextField();
        button_thanhtoan = new javax.swing.JButton();
        panel_dichvu = new javax.swing.JPanel();
        button_casino = new javax.swing.JButton();
        button_ok = new javax.swing.JButton();
        button_spa = new javax.swing.JButton();
        button_bar = new javax.swing.JButton();
        button_tennis = new javax.swing.JButton();
        button_hoihop = new javax.swing.JButton();
        button_nhahang = new javax.swing.JButton();
        button_fitness = new javax.swing.JButton();
        button_golf = new javax.swing.JButton();
        text_tiendichvu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Table.setEnabled(false);
        Table.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Table.setVerifyInputWhenFocusTarget(false);

        button_dangnhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_dangnhap.setText("Đăng nhập");
        button_dangnhap.setEnabled(false);
        button_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dangnhapActionPerformed(evt);
            }
        });

        button_connect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_connect.setText("Kết nối thẻ");
        button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connectActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PIN:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(button_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_connect, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        Table.addTab("Đăng nhập", jPanel4);

        button_1.setBackground(new java.awt.Color(255, 255, 255));
        button_1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_1.setText("Phòng 1");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        button_2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_2.setText("Phòng 2");
        button_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_2ActionPerformed(evt);
            }
        });

        button_3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_3.setText("Phòng 3");
        button_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_3ActionPerformed(evt);
            }
        });

        button_5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_5.setText("Phòng 5");
        button_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_5ActionPerformed(evt);
            }
        });

        button_6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_6.setText("Phòng 6");
        button_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_6ActionPerformed(evt);
            }
        });

        button_7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_7.setText("Phòng 7");
        button_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_7ActionPerformed(evt);
            }
        });

        button_8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_8.setText("Phòng 8");
        button_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_8ActionPerformed(evt);
            }
        });

        button_4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button_4.setText("Phòng 4");
        button_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_mokhoaphongLayout = new javax.swing.GroupLayout(panel_mokhoaphong);
        panel_mokhoaphong.setLayout(panel_mokhoaphongLayout);
        panel_mokhoaphongLayout.setHorizontalGroup(
            panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mokhoaphongLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel_mokhoaphongLayout.setVerticalGroup(
            panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mokhoaphongLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(panel_mokhoaphongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        Table.addTab("Mở khóa phòng", panel_mokhoaphong);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Số CCCD:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên chủ thẻ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Phòng:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngày ĐK:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("PIN:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tiền trong thẻ:");

        button_doimapin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_doimapin.setText("Đổi mã pin");
        button_doimapin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_doimapinActionPerformed(evt);
            }
        });

        text_cccd.setEnabled(false);

        text_hoten.setEnabled(false);

        text_phong.setEnabled(false);

        text_ngaydk.setEnabled(false);

        text_tien.setEnabled(false);
        text_tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_tienActionPerformed(evt);
            }
        });

        anhdaidien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Ảnh đại diện");

        javax.swing.GroupLayout panel_thongtincanhanLayout = new javax.swing.GroupLayout(panel_thongtincanhan);
        panel_thongtincanhan.setLayout(panel_thongtincanhanLayout);
        panel_thongtincanhanLayout.setHorizontalGroup(
            panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(text_cccd))
                            .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                                    .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(51, 51, 51)
                                    .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(text_tien, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                                                .addComponent(text_mapin)
                                                .addComponent(text_ngaydk))
                                            .addComponent(text_phong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(text_hoten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(52, 52, 52)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(anhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(button_doimapin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_thongtincanhanLayout.setVerticalGroup(
            panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(text_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_ngaydk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(anhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_mapin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(panel_thongtincanhanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(panel_thongtincanhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(button_doimapin)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        Table.addTab("Thông in cá nhân", panel_thongtincanhan);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Nhập số tiền cần thanh toán");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Số tiền cần thanh toán");

        button_thanhtoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_thanhtoan.setText("Thanh toán");
        button_thanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_thanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_tiencanthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_tiennhapvao, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(button_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(text_tiencanthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_tiennhapvao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addComponent(button_thanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        Table.addTab("Thanh toán thẻ", jPanel1);

        button_casino.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_casino.setText("Casino");
        button_casino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_casinoActionPerformed(evt);
            }
        });

        button_ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_spa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_spa.setText("Spa");
        button_spa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_spaActionPerformed(evt);
            }
        });

        button_bar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_bar.setText("Bar");
        button_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_barActionPerformed(evt);
            }
        });

        button_tennis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_tennis.setText("Tennis");
        button_tennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_tennisActionPerformed(evt);
            }
        });

        button_hoihop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_hoihop.setText("Hội họp");
        button_hoihop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_hoihopActionPerformed(evt);
            }
        });

        button_nhahang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_nhahang.setText("Nhà Hàng");
        button_nhahang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_nhahangActionPerformed(evt);
            }
        });

        button_fitness.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_fitness.setText("Fitness");
        button_fitness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_fitnessActionPerformed(evt);
            }
        });

        button_golf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_golf.setText("Golf");
        button_golf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_golfActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tiền dịch vụ:");

        javax.swing.GroupLayout panel_dichvuLayout = new javax.swing.GroupLayout(panel_dichvu);
        panel_dichvu.setLayout(panel_dichvuLayout);
        panel_dichvuLayout.setHorizontalGroup(
            panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_dichvuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addComponent(button_casino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(button_spa, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_bar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_fitness, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_hoihop, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_dichvuLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_nhahang, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_tiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tennis, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_golf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        panel_dichvuLayout.setVerticalGroup(
            panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dichvuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_casino, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_spa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_tennis, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_golf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_fitness, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_nhahang, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_hoihop, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(button_ok))
                    .addGroup(panel_dichvuLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(panel_dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_tiendichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Table.addTab("Dịch vụ yêu cầu", panel_dichvu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Table)
        );

        Table.getAccessibleContext().setAccessibleName("");
        Table.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_tienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_tienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_tienActionPerformed

    private void button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connectActionPerformed
      if(!isConnect){
            if(host.connectapplet()){         
               isConnect=true;
               button_dangnhap.setEnabled(true);
           }else{
                JOptionPane.showMessageDialog(this, "Chưa connect được đến applet");
                isConnect = false;
           }
       }else{
       }        
    }//GEN-LAST:event_button_connectActionPerformed

    public String mapin2;
    private void button_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dangnhapActionPerformed
                      
      String pin = new String(text_pin.getPassword());
      if (pin.length() == 6) {
            String checkPIN = host.authPIN(pin);
            System.out.println(checkPIN+"faewfawefwa");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                        Table.setEnabled(true);             
                        anhdaidien.setIcon(new ImageIcon( host.DownloadImage()));           
                        String[] data = host.getData().split("@");
                        text_cccd.setText(data[0]);
                        text_hoten.setText(data[1]);                       
                        text_phong.setText(data[4]);
                        text_ngaydk.setText(data[5]);
                        text_mapin.setText(data[6]);
                        text_tien.setText(data[7]);    
                        text_tiencanthanhtoan.setText(tienthuc+data[7]);
                        mapin2 = data[6];
                        tienthuc = Integer.valueOf(data[7]);
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Nhập mã sai rồi đấy");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Thẻ đã bị khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi đăng nhập");
                        break;
        }}else{
       JOptionPane.showMessageDialog(rootPane, "Mật khẩu phải gồm 6 số");
      }
    }//GEN-LAST:event_button_dangnhapActionPerformed

    private void button_doimapinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_doimapinActionPerformed
        if(!text_mapin.getText().equals(mapin2)){
            System.out.println("thay doi pin");
            if(host.changePIN(text_mapin.getText())){
                System.out.println("thay doi pin  thanh cong");
                JOptionPane.showMessageDialog(this, "Thay pin thành công");   
            }
        }
    }//GEN-LAST:event_button_doimapinActionPerformed

    private void button_casinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_casinoActionPerformed
        // TODO add your handling code here:
        tiendichvu +=100;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_casinoActionPerformed

    private void button_spaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_spaActionPerformed
       tiendichvu +=200;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_spaActionPerformed

    private void button_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_barActionPerformed
        // TODO add your handling code here:
         tiendichvu +=300;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_barActionPerformed

    private void button_tennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_tennisActionPerformed
        // TODO add your handling code here:
         tiendichvu +=400;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_tennisActionPerformed

    private void button_hoihopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_hoihopActionPerformed
        tiendichvu +=500;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_hoihopActionPerformed

    private void button_nhahangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_nhahangActionPerformed
        // TODO add your handling code here:
         tiendichvu +=600;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_nhahangActionPerformed

    private void button_fitnessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_fitnessActionPerformed
        tiendichvu +=700;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_fitnessActionPerformed

    private void button_golfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_golfActionPerformed
       tiendichvu +=800;
        text_tiendichvu.setText(tiendichvu+"");
    }//GEN-LAST:event_button_golfActionPerformed

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        // TODO add your handling code here:
        tienthuc+= tiendichvu;
        text_tien.setText(tienthuc+"");
        text_tiencanthanhtoan.setText(tienthuc+"");
        host.changeWallet(tienthuc+"");
        JOptionPane.showMessageDialog(this, "Rất vui lòng phục vụ quý khách");   
    }//GEN-LAST:event_button_okActionPerformed

    private void button_thanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_thanhtoanActionPerformed
        // TODO add your handling code here:
        int tien3 = Integer.valueOf(text_tiencanthanhtoan.getText());
        int tiennhapvao = Integer.valueOf(text_tiennhapvao.getText());
        if(tiennhapvao>tien3){
              JOptionPane.showMessageDialog(this, "Số tiền phải nhỏ hơn số tiền cần thanh toán");
        }
        else{
           int b = tien3-tiennhapvao;
           text_tien.setText(b+"");
           text_tiencanthanhtoan.setText(b+"");
           host.changeWallet(b+"");
           JOptionPane.showMessageDialog(this, "Thanh toán thành công");   
        }  
    }//GEN-LAST:event_button_thanhtoanActionPerformed

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
            String maphong = "01";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_1ActionPerformed

    private void button_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_2ActionPerformed
        // TODO add your handling code here:
         String maphong = "02";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_2ActionPerformed

    private void button_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_3ActionPerformed
       String maphong = "03";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_3ActionPerformed

    private void button_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_4ActionPerformed
       String maphong = "04";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_4ActionPerformed

    private void button_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_5ActionPerformed
         String maphong = "05";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_5ActionPerformed

    private void button_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_6ActionPerformed
       String maphong = "06";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_6ActionPerformed

    private void button_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_7ActionPerformed
            String maphong = "07";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_7ActionPerformed

    private void button_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_8ActionPerformed
            String maphong = "08";
     
            String checkPIN = host.authPHONG(maphong);
            System.out.println("dang check phong");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Mở khóa cửa thành công");                    
                        break;

                    case "19000":
                        JOptionPane.showMessageDialog(this, "Không mở khóa cửa thành công");
                        break;
                     
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Lỗi khóa");
                    
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi mở khóa");
                        break;
             }
    }//GEN-LAST:event_button_8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Table;
    private javax.swing.JLabel anhdaidien;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_bar;
    private javax.swing.JButton button_casino;
    private javax.swing.JButton button_connect;
    private javax.swing.JButton button_dangnhap;
    private javax.swing.JButton button_doimapin;
    private javax.swing.JButton button_fitness;
    private javax.swing.JButton button_golf;
    private javax.swing.JButton button_hoihop;
    private javax.swing.JButton button_nhahang;
    private javax.swing.JButton button_ok;
    private javax.swing.JButton button_spa;
    private javax.swing.JButton button_tennis;
    private javax.swing.JButton button_thanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel panel_dichvu;
    private javax.swing.JPanel panel_mokhoaphong;
    private javax.swing.JPanel panel_thongtincanhan;
    private javax.swing.JTextField text_cccd;
    private javax.swing.JTextField text_hoten;
    private javax.swing.JTextField text_mapin;
    private javax.swing.JTextField text_ngaydk;
    private javax.swing.JTextField text_phong;
    private javax.swing.JPasswordField text_pin;
    private javax.swing.JTextField text_tien;
    private javax.swing.JTextField text_tiencanthanhtoan;
    private javax.swing.JTextField text_tiendichvu;
    private javax.swing.JTextField text_tiennhapvao;
    // End of variables declaration//GEN-END:variables
}
