/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartcard03;
//import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
//import java.security.*;
//import java.math.BigInteger;
//import java.security.InvalidKeyException;
//import java.security.KeyFactory;
//import java.security.NoSuchAlgorithmException;
//import java.security.PublicKey;
//import java.security.Signature;
//import java.security.SignatureException;
//import java.security.spec.InvalidKeySpecException;
//import java.security.spec.RSAPublicKeySpec;
//import java.util.Base64;
//import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import java.awt.Color;
import java.math.BigInteger;
import java.util.Random;
import java.security.*;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.RSAPublicKeySpec;
import java.util.Arrays;
import java.util.Base64;
import javax.swing.JOptionPane;

/**
 *
 * @author laihi
 */
public class MainFrame extends javax.swing.JFrame {

    private ConnectJavaCard host;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        host = new ConnectJavaCard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button_ok = new javax.swing.JButton();
        button_connect = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        text_status = new javax.swing.JTextField();
        button_init = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        text_checkpin = new javax.swing.JPasswordField();
        testbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_cccd = new javax.swing.JTextField();
        text_hoten = new javax.swing.JTextField();
        text_ngaysinh = new javax.swing.JTextField();
        text_sdt = new javax.swing.JTextField();
        text_phong = new javax.swing.JTextField();
        text_ngaydk = new javax.swing.JTextField();
        Anhdaidien = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_doiten = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        text_tien = new javax.swing.JTextField();
        btn_doingaysinh = new javax.swing.JButton();
        btn_doisodienthoai = new javax.swing.JButton();
        btn_doiphong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kết Nối", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(51, 51, 255))); // NOI18N

        button_ok.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_ok.setText("Đồng ý");
        button_ok.setEnabled(false);
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });

        button_connect.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_connect.setText("Kết nối đến thẻ");
        button_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_connectActionPerformed(evt);
            }
        });

        jLabel8.setText("Trạng thái");

        button_init.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_init.setText("Khởi tạo thẻ mới");
        button_init.setEnabled(false);
        button_init.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_initActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("Mở thẻ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        button_delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        button_delete.setText("Xóa thẻ");
        button_delete.setEnabled(false);
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        jLabel9.setText("Nhập mã PIN:");

        text_checkpin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_checkpinActionPerformed(evt);
            }
        });

        testbtn.setText("jButton2");
        testbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_checkpin)
                    .addComponent(button_connect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_init, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_status))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(button_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(button_ok, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(testbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_connect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_status, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(button_init)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(button_delete)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_checkpin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button_ok)
                .addGap(28, 28, 28)
                .addComponent(testbtn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Thẻ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 20), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Số CCCD:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên chủ thẻ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Ngày sinh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("SĐT:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Phòng:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ngày ĐK:");

        text_cccd.setEnabled(false);

        text_ngaydk.setEnabled(false);
        text_ngaydk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_ngaydkActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel10.setText("Ảnh đại diện");

        btn_doiten.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_doiten.setText("Đổi tên");
        btn_doiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doitenActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Tiền:");

        text_tien.setEnabled(false);

        btn_doingaysinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_doingaysinh.setText("Đổi NS");
        btn_doingaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doingaysinhActionPerformed(evt);
            }
        });

        btn_doisodienthoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_doisodienthoai.setText("Đổi SĐT");
        btn_doisodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doisodienthoaiActionPerformed(evt);
            }
        });

        btn_doiphong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_doiphong.setText("Đổi Phòng");
        btn_doiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiphongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(Anhdaidien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_ngaydk, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_doiten, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_doingaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_doisodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_doiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_cccd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_phong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Anhdaidien, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(text_ngaydk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_tien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_doiten, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_doingaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_doisodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_doiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_doiten.getAccessibleContext().setAccessibleName("Đổi tên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isConnect = false;
    private void button_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_connectActionPerformed
       //host.connectapplet();
       if(!isConnect){
            if(host.connectapplet()){
               button_connect.setText("Ngắt kết nối");
               isConnect=true;
               text_status.setText("Thành công");
               button_delete.setEnabled(isConnect);
               button_init.setEnabled(isConnect);
               button_ok.setEnabled(isConnect);
           }else{
                JOptionPane.showMessageDialog(this, "Chưa connect được đến applet");
                isConnect = false;
                button_connect.setText("Kết nối đến thẻ");
                text_status.setText("0 Thành công");
           }
       }else{
            if (host.disconnect()) {
                isConnect = false;
                button_connect.setText("Kết nối đến thẻ");
                text_status.setText("");
                button_delete.setEnabled(isConnect);
                button_init.setEnabled(isConnect);
                button_ok.setEnabled(isConnect);
                text_checkpin.setText("");
                text_cccd.setText("");
                text_hoten.setText("");
                text_ngaysinh.setText("");
                text_sdt.setText("");
                text_phong.setText("");
                text_ngaydk.setText("");
                text_tien.setText("");
                Anhdaidien.setIcon(null); 
            }      
       }
    }//GEN-LAST:event_button_connectActionPerformed
    
    public String hoten2;
    public String ngaysinh2;
    public String sdt2;
    public String phong2;
    public int tien2;
    int count=0;
    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_okActionPerformed
        String pin = new String(text_checkpin.getPassword());
        if (pin.length() == 6) {
            String checkPIN = host.authPIN(pin);
            System.out.println(checkPIN+"faewfawefwa");
            
             switch (checkPIN) {
                    case "9000":
                        JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                           count=0;
                           
                           String[] data = host.getData().split("@");
                           System.out.println("-----------"+data.length);
                           text_cccd.setText(data[0]);
                           text_hoten.setText(data[1]);
                           System.out.println(" dich vu yeu cau hien gio la" + data[2]);
                           text_ngaysinh.setText(data[3]);
                           text_sdt.setText(data[4]);
                           text_phong.setText(data[5]);
                           text_ngaydk.setText(data[6]);
                           text_tien.setText(data[7]); 
                           Anhdaidien.setIcon(new ImageIcon( host.DownloadImage())); 
                           hoten2=data[1];
                           ngaysinh2=data[3];
                           sdt2=data[4];
                           phong2=data[5];
                           tien2 = Integer.valueOf(data[7]);                                         
                           break;
                    case "19000":
                       // host.wrongPIN();
                        JOptionPane.showMessageDialog(this, "Còn " + (3-count) + " nhập sai PIN");
                        count++;
                        break;                   
                    case "09000":
                        JOptionPane.showMessageDialog(this, "Thẻ đã bị khóa");                  
                        break;
                    default:
                        JOptionPane.showMessageDialog(rootPane, "Lỗi đăng nhập");
                        break;
        }}else{
       JOptionPane.showMessageDialog(rootPane, "Mật khẩu phải gồm 6 số");
      }                         
    }//GEN-LAST:event_button_okActionPerformed

    private void button_initActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_initActionPerformed
        // TODO add your handling code here:
        TaoTheMoi fkt = new TaoTheMoi();
        fkt.setVisible(true);     
        fkt.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_button_initActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(host.unLock()){
             JOptionPane.showMessageDialog(rootPane, "Unlock thẻ thành công");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
       if(host.disconnect()){
            isConnect = false;
            button_connect.setText("Kết nối đến thẻ");
            text_cccd.setText("");
            text_hoten.setText("");
            text_ngaysinh.setText("");
            text_sdt.setText("");
            text_phong.setText("");
            text_ngaydk.setText("");
            text_status.setText("");
            button_delete.setEnabled(isConnect);
            button_init.setEnabled(isConnect);
            text_checkpin.setText("");
            button_ok.setEnabled(isConnect);
            Anhdaidien.setIcon(null);
       }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void text_ngaydkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_ngaydkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_ngaydkActionPerformed

    private void text_checkpinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_checkpinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_checkpinActionPerformed

    boolean resu1t = true;
    private void btn_doitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doitenActionPerformed
        // TODO add your handling code here:
        if(!text_hoten.getText().equals(hoten2)){
            System.out.println("thay doi ho ten");
            if(host.changeName(text_hoten.getText())){
                 System.out.println("thay doi ho ten thanh cong");
                  JOptionPane.showMessageDialog(this, "Cập nhập họ tên thành công");   
            }
        }
        
//        if(!text_sdt.getText().equals(sdt2)){
//            System.out.println("thay doi sdt");
//              if(host.changePhoneNumber(text_sdt.getText())){
//                 System.out.println("thay doi sdt thanh cong");
//            }
//        }
       
                
//        Anhdaidien.setIcon(new ImageIcon( host.DownloadImage()));           
//        String[] data = host.getData().split("@");
//        text_cccd.setText(data[0]);
//        text_hoten.setText(data[1]);
//        text_ngaysinh.setText(data[3]);
//        text_sdt.setText(data[4]);
//        text_phong.setText(data[5]);
//        text_ngaydk.setText(data[6]);
//        System.out.println("Cap nhap lai he thong");
       
    }//GEN-LAST:event_btn_doitenActionPerformed

     boolean result = false;
    private void testbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testbtnActionPerformed
        String ranString = randomString().toLowerCase();
        byte[] dataBytes = Base64.getEncoder().encode(ranString.getBytes());
        String resData = host.authCard(ranString);
        String resRanString = resData.substring(128);
        try {
            String expAndMod =  ConnectJavaCard.idAndPubkey.get("123456");
            System.out.println(expAndMod); 
            String exp = expAndMod.substring(0, 6);
            String mod = expAndMod.substring(6);
            RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(new BigInteger(mod, 16), new BigInteger(exp,16));
            KeyFactory factory = KeyFactory.getInstance("RSA");
            PublicKey pubKey = factory.generatePublic(pubKeySpec);
            Signature signature = Signature.getInstance("SHA1withRSA");
            signature.initVerify(pubKey);
            signature.update(dataBytes);
            result = signature.verify(resRanString.getBytes());
            if(resu1t==true){
               JOptionPane.showMessageDialog(rootPane, "Xác thực thành công");
            }else{
               JOptionPane.showMessageDialog(rootPane, "Xác thực thất bại"); 
            }
            System.out.println(resu1t);          
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | InvalidKeyException | SignatureException  e) {
            System.out.println("Error" + e);
        } 
           
    }//GEN-LAST:event_testbtnActionPerformed

    private void btn_doingaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doingaysinhActionPerformed
        if(!text_ngaysinh.getText().equals(ngaysinh2)){
            System.out.println("thay doi ngay sinh");
            if(host.changeBirth(text_ngaysinh.getText())){
                System.out.println("thay doi ngay sinh thanh cong");
                 JOptionPane.showMessageDialog(this, "Cập nhập ngày sinh thành công");   
            }
        }
    }//GEN-LAST:event_btn_doingaysinhActionPerformed

    private void btn_doisodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doisodienthoaiActionPerformed
        // TODO add your handling code here:
        if(!text_sdt.getText().equals(sdt2)){
            System.out.println("thay doi sdt");
              if(host.changePhoneNumber(text_sdt.getText())){
                 System.out.println("thay doi sdt thanh cong");
                  JOptionPane.showMessageDialog(this, "Cập nhập sdt thành công");   
            }
        }
    }//GEN-LAST:event_btn_doisodienthoaiActionPerformed

    private void btn_doiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiphongActionPerformed
        // TODO add your handling code here:
         if(!text_phong.getText().equals(phong2)){
            System.out.println("thay doi phong");
            if(host.changeRoom(text_phong.getText())){
                 System.out.println("thay doi phong thanh cong");
                  JOptionPane.showMessageDialog(this, "Cập nhập phòng thành công");   
            }
        }
    }//GEN-LAST:event_btn_doiphongActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
     public String randomString() {
        String SALTCHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
        StringBuilder salt = new StringBuilder();
        Random rnd = new Random();
        while (salt.length() < 3) {
            int index = (int) (rnd.nextFloat() * SALTCHARS.length());
            salt.append(SALTCHARS.charAt(index));
        }
        String saltStr = salt.toString();
        return saltStr;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anhdaidien;
    private javax.swing.JButton btn_doingaysinh;
    private javax.swing.JButton btn_doiphong;
    private javax.swing.JButton btn_doisodienthoai;
    private javax.swing.JButton btn_doiten;
    private javax.swing.JButton button_connect;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_init;
    private javax.swing.JButton button_ok;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton testbtn;
    private javax.swing.JTextField text_cccd;
    private javax.swing.JPasswordField text_checkpin;
    private javax.swing.JTextField text_hoten;
    private javax.swing.JTextField text_ngaydk;
    private javax.swing.JTextField text_ngaysinh;
    private javax.swing.JTextField text_phong;
    private javax.swing.JTextField text_sdt;
    private javax.swing.JTextField text_status;
    private javax.swing.JTextField text_tien;
    // End of variables declaration//GEN-END:variables
}
